sonar.organization=SURF-Research-Agents
sonar.projectKey=SURF-Research-Agents_langchain_surf
sonar.host.url=https://sonarcloud.io
sonar.sources=src/langchain_surf/
sonar.tests=tests/
sonar.links.homepage=https://github.com/SURF-Research-Agents/langchain_surf
sonar.links.scm=git@github.com:SURF-Research-Agents/langchain_surf
sonar.links.issue=https://github.com/SURF-Research-Agents/langchain_surf/issues
sonar.links.ci=https://github.com/SURF-Research-Agents/langchain_surf/actions
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=xunit-result.xml
sonar.python.pylint.reportPaths=pylint-report.txt
